name: flutter_connectivity_test
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  #ffi: ^2.0.1
  connectivity_plus: ^6.0.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1    # display local notifications
  timezone: ^0.10.0                        # get the local timezone
  #flutter_native_timezone: ^2.0.0        # get the local timezone
  rxdart: ^0.28.0                         # create and listen to event streams
  path_provider: ^2.1.4                   # work with the device file system
  http: ^1.2.2                            # make HTTP requests
  flutter_localizations:
    sdk: flutter
  dart_ping: ^9.0.1
  #dart_ping_ios: ^4.0.2
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.14.3
  flutter_speed_test_plus: ^1.0.10
  flutter_spinkit: ^5.2.1
  mrx_charts: ^0.1.3
  shared_preferences: ^2.5.1  
  url_launcher: ^6.1.11
  flutter_background_service: ^5.1.0
  #workmanager: ^0.5.1
  permission_handler: ^11.3.1
  numberpicker: ^2.1.2
  #wifi_iot: ^0.3.19+2
  android_intent_plus: ^5.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_native_splash:
  color: "#ffffff" # Background color
  image: "assets/images/logo_half2.png" # Path to your splash logo image
  android: true
  ios: true
  fullscreen: true

#flutter pub run flutter_launcher_icons -f <your config file name here> , so basicly pubspec.yaml to create icons for all devices
#flutter pub run flutter_launcher_icons -f pubspec.yaml
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"
